openapi: 3.0.0
info:
  version: 0.1.0
  title: VCMS REST API
  description: |-
    Tài liệu hướng dẫn sử dụng API của VCMS. Các API có chức năng sau:

    - Lọc nội dung nhạy cảm như chiến tranh, thiên tai, cờ bạc, tai nạn và các hình ảnh từ ngữ không phù hợp xuất hiện trong video (youtube). 
    - Nhận diện văn bản trong hình ảnh.
  contact:
    name: VCMS Developer Support
    email: hieptran.jobs@gmail.com
servers:
  - url: 'http://<ip-custom>'
    description: Production server
paths:
  '/ocr_image':
    summary: Ocr từ file hình ảnh
    post:
      summary: Ocr từ file hình ảnh
      description: Nhận diện văn bản từ file hình ảnh
      tags:
        - Hình ảnh
      requestBody:
        application/json:
          schema:
            type: object
            properties:
              image:
                type: string
                format: binary
      responses:
        '200':
          description: Success response
          content:
            application/json:

      security:
        - APIKEY: []
    get:
      summary: Ocr từ link hình ảnh
      description: Ocr từ link hình ảnh
      tags:
        - Hình ảnh
      parameters:
        - in: query
          name: img_url
          schema:
            type: string
          description: Link ảnh
      responses:
        '200':
          description: Success response
          content:
            application/json:
      security:
        - APIKEY: []
  '/video_content_moderation':
    get:
      summary: Video content moderation
      description: Video content moderation
      tags:
        - Video
      parameters:
        - in: query
          name: url_vid
          schema:
            type: string
          description: Link video
      responses:
        '200':
          description: Success response
          content:
            application/json:
      security:
        - APIKEY: []
tags:
  - name: Hình ảnh
  - name: Video
